### ISSUE TITLE
Latest version in NPM

### ISSUE THREAD

**Issue by tomhallam** [dougmoscrop/serverless-http#115]
Hey @dougmoscrop,

Are you able to publish the latest version to NPM please? I'd like to use the mainline version rather than my fork in my current project.

Thanks a lot,
Tom

**Comment by dougmoscrop** [comment]
Yep, will do

**Comment by dougmoscrop** [comment]
Done (2.1.0) - was a small bug (https://github.com/dougmoscrop/serverless-http/commit/e4e34ddf1e472c324d64db0832a5e9edbc55e5fa#diff-3ca005ad9556adb0ddcf1ff3c3c37f4fL18) but let me know if anything else does not work
