### ISSUE TITLE
Support request ID

### ISSUE THREAD

**Issue by rochdev** [dougmoscrop/serverless-http#12]
The event provided by AWS contains a generated request ID in the request context. It would be interesting to have that automatically injected as a header. The de facto standard would be `X-Request-ID` (ref. https://en.wikipedia.org/wiki/List_of_HTTP_header_fields#Common_non-standard_request_fields)

**Comment by rochdev** [comment]
I don't think `true` is needed in that case. Could just be:

* string (defaults to `X-Request-ID`)
* false (disable)

**Comment by dougmoscrop** [comment]
Yeah. I just meant if someone sent `true` I would just convert it rather than throw an error ;)

**Comment by dougmoscrop** [comment]
Ok, I've implemented this. I didn't bother with `true`, you were right :)

**Comment by rochdev** [comment]
@dougmoscrop Any idea when this will land? I want to get going on #11 but since both features introduce an `options` parameter I'd rather wait for this to be merged.

**Comment by dougmoscrop** [comment]
Will do today!

**Comment by dougmoscrop** [comment]
Done via 1.3

**Comment by rochdev** [comment]
@dougmoscrop I don't think mutating the event object directly is recommended. Would it be possible to add the header directly to the request object instead?

**Comment by dougmoscrop** [comment]
Refactored to avoid mutating event object:

https://github.com/dougmoscrop/serverless-http/commit/6b8669c0de70aae639b55aac437811a1139e99e6
