### ISSUE TITLE
Encoding issues with fs.pipe & images?

### ISSUE THREAD

**Issue by btakita** [dougmoscrop/serverless-http#122]
I'm using sirv to serve static images. Serve uses [the following](https://github.com/lukeed/sirv/blob/master/packages/sirv/index.js#L69) to write the file to the response stream.

```javascript
fs.createReadStream(file, opts).pipe(res);
```

I'm getting a corrupted image with random pixels.
Does serverless-http support `fs.pipe` or is this an issue?

**Comment by btakita** [comment]
I'm also getting corruption issues using the `serve-static` library, which also uses `fs.pipe`.

Attached is the original image & the served image.

![favicon](https://user-images.githubusercontent.com/3664/64069324-905e7600-cc15-11e9-8112-2c4343a16d38.png)

![favicon serverless-http](https://user-images.githubusercontent.com/3664/64069321-82a8f080-cc15-11e9-97b1-2689a820d089.png)

**Comment by dougmoscrop** [comment]
Are you sure your API gateway is correctly configured to handle binary content encoding and so on?

**Comment by btakita** [comment]
You're right. The API gateway `BinaryMediaTypes` & `serverless-http` `global` option needs to be configured.

```yaml
Globals:
  Api:
    BinaryMediaTypes:
      - image~1png
      - image~1gif
      - image~1jpg
      - image~1jpeg
      - image~1x-icon
```

```js
import serverless from 'serverless-http'
const handler__serverless = serverless(app, {
	binary(headers) {
		return true
	},
})
module.exports.handler = handler__serverless
```
