### ISSUE TITLE
res.writeHead ignoring headers (2.3.0)

### ISSUE THREAD

**Issue by BaukePalstra** [dougmoscrop/serverless-http#157]
When implementing `res.writeHead`, I get no headers back in my response:
`
(req, res) => { 
  res.writeHead(301, {
    Location: ' /foo',
  })  
  res.end()`
}
results in this response:
`{
  "statusCode": 301,
  "headers": {},
  "isBase64Encoded": false,
  "body": ""
}`

This is working fine without serverless http (ServerResponse instead of ServerlessResponse). 

I suspect it has to do with https://github.com/dougmoscrop/serverless-http/blob/master/lib/response.js#L41, since the key is named `_header`, instead of `_headers` .

Refactoring to `res.setHeader('Location', ' /foo')
  res.statusCode = 301
  res.end()` does give the response I expect

**Comment by dougmoscrop** [comment]
I added a test that shows this is working - can you double-check? https://github.com/dougmoscrop/serverless-http/blob/master/test/spec.js#L400

**Comment by BaukePalstra** [comment]
Sorry for the late reply. I see that in the 2.3.1 (title wrongfully says 2.3.0) version, writeHead wasn't working. I've added your test to that version (locally), but it errs: 
![image](https://user-images.githubusercontent.com/13105978/82435686-f08f9380-9a94-11ea-858a-d2ebaf30a063.png)
.

Indeed looks like everything is ok now 👍

**Comment by dougmoscrop** [comment]
Great! So OK to close this?
