### ISSUE TITLE
TypeError: Cannot set property 'corked' of undefined

### ISSUE THREAD

**Issue by adamnoakes** [dougmoscrop/serverless-http#158]
100% reproducible for me in v2.4.0. 2.3.2 is fine.

I'm using koa:

```javascript
import serverless from 'serverless-http';
import Koa from 'koa';

const app = new Koa();

app.use(ctx => {
  ctx.body = 'Hello World';
});
module.exports.handler = serverless(app);
```

results in internal server error on AWS Lambda. Logs from lambda:
```
START RequestId: 6cd82d09-b15f-4220-b510-bdd58c9a9334 Version: $LATEST
15:20:33
2020-05-11T15:20:33.424Z 6cd82d09-b15f-4220-b510-bdd58c9a9334 ERROR undefined
15:20:33
2020-05-11T15:20:33.424Z 6cd82d09-b15f-4220-b510-bdd58c9a9334 ERROR TypeError: Cannot set property 'corked' of undefined at ServerlessResponse.end (_http_outgoing.js:780:39) at respond (/var/task/node_modules/koa/lib/application.js:255:43) at handleResponse (/var/task/node_modules/koa/lib/application.js:164:34)
15:20:33
2020-05-11T15:20:33.424Z 6cd82d09-b15f-4220-b510-bdd58c9a9334 ERROR undefined
15:20:33
END RequestId: 6cd82d09-b15f-4220-b510-bdd58c9a9334```

**Comment by dougmoscrop** [comment]
What version of Node?

**Comment by dougmoscrop** [comment]
oh, and version of Koa

**Comment by dougmoscrop** [comment]
Try 2.4.1, but I'd still like to know what version(s) as I wrote a test and could not reproduce it, probably because of what version of Koa I was using

**Comment by adamnoakes** [comment]
Node.js 12, i never tried 10.

**Comment by adamnoakes** [comment]
> Try 2.4.1, but I'd still like to know what version(s) as I wrote a test and could not reproduce it, probably because of what version of Koa I was using

2.4.1 appears to be working 👍

**Comment by dougmoscrop** [comment]
okay great, sorry about that!

**Comment by AOlefirenko** [comment]
I've got the problem after upgrading from 2.3.2 to 2.4.0 
Express 4.17.1
Node.js 12

2.4.1 helped :)

**Comment by adamnoakes** [comment]
No problem, thanks for patching so quickly.
