### ISSUE TITLE
How to get AWS Account ID

### ISSUE THREAD

**Issue by ngoyal16** [dougmoscrop/serverless-http#183]
IF we use AWS IAM as autenitication then How we can get the AWS Account ID of caller with caller username

**Comment by dougmoscrop** [comment]
I am not sure, we don't use IAM auth for anything other than pure Lambda invocations.  Where would you normally obtain this? The context object?  If so, there are ways to attach that to the request, maybe we can make that consistent.

**Comment by ngoyal16** [comment]
i already got where to find the account id and working fine

**Comment by vadymhimself** [comment]
@dougmoscrop how to attach the context to request?
