### ISSUE TITLE
Getting restana out of the experimental flag

### ISSUE THREAD

**Issue by jkyberneees** [dougmoscrop/serverless-http#187]
> First of all, congratulations for such a great project!!!

**Hi here, I was wondering about the required criteria for getting a listed framework out of the experimental flag?**

I am the autor of the `restana` framework. But also, `fast-gatetway` and `http-lambda-proxy`; a high performance stack that follows the intention of simplifying the migration of REST based micro-service architectures into the serverless world using AWS Lambda.

There are several benefits of using restana, especially in the context of lambda, I could just mention performance and size.  
Therefore, the potential when combined with this module!

Looking forward to your considerations.

Regards

**Comment by dougmoscrop** [comment]
Hey! Thanks for reaching out! I will 100% move it out of experimental if you can vouch that the way we dispatch the (req, res) objects to them is not outright wrong, I put it as experimental only in the sense that I am not running things that are using it so I haven't had time to exercise it.  If there are other tests we should add I would like to hear that too.

So yeah it's largely a product of how much use it has seen

**Comment by jkyberneees** [comment]
Hi @dougmoscrop, many thanks for your followup. 

`restana` could be considered a minimalist express-like framework. It basically works with plain/standard Node.js HTTP req/res objects, so no especial wrapping or modification is required, other than adding a `send` method. 
This module is compatible with restana, no other special tests have to be added. 

> Please let me know if you would need any other information.

Regards

**Comment by dougmoscrop** [comment]
Sounds good, I'm happy to remove the flag!

**Comment by dougmoscrop** [comment]
Done :)
