### ISSUE TITLE
More detailed example(s)

### ISSUE THREAD

**Issue by barczaG** [dougmoscrop/serverless-http#20]
Can you please provide some more detailed example? 
I still don't get how can I define a "catch all" handler in my `serverless.yml`

**Comment by dougmoscrop** [comment]
Will do

**Comment by dougmoscrop** [comment]
Does this help? https://github.com/dougmoscrop/serverless-http/blob/master/docs/EXAMPLES.md

**Comment by barczaG** [comment]
Yes, it is! Thanks.
