### ISSUE TITLE
A question on an asynchronous setup

### ISSUE THREAD

**Issue by djalbat** [dougmoscrop/serverless-http#202]
Hi!

The following files have been shortened for clarlity:

I have a the following `app.js`:

```
const express = require("express");

async function createApp() {
  const app = express();

  app.use(...);

  return app;
}

module.exports = {
  createApp
};
```

I can run this easily enough outside of a lambda in `main.js`:

```
const { createApp } = require('./app');

(async function() {
  const app = await createApp();

  app.listen();
})();
```

I thought I could adapt this anonymous asynchronous function approach to a lambda `lambda.js` thus...

```
const serverless = require("serverless-http"); ///

const { createApp } = require("./app");

module.exports.handler = (async function() {
  const app = await createApp();

  return serverless(app);
})();
```
I understand that this won't work because the asynchronous function call will just return `undefined`, but I don't know how to correct it. I wonder if something along these lines is even possible.

Do you have any suggestions?

Many thanks and kind regards,
James

**Comment by vitalii-kyktov** [comment]
I am also curious on a proper way to perform async setup. Now when I'm returning `Promise<express.Application>` then getting
```
Error: Unsupported framework
    at getFramework (/var/task/_express/node_modules/serverless-http/lib/framework/get-framework.js:69:9)
    at module.exports (/var/task/_express/node_modules/serverless-http/serverless-http.js:14:21)
```

**Comment by djalbat** [comment]
Hello Vitaly,

I am glad someone else has this problem! However, I realised after opening the issue that it is not really the maintainer's problem but a more generic one.

To get around it I moved the asynchronous call to a handler and called it explicitly by way of an endpoint. Then I could export the application synchronously as usual. I hope this helps.

Kind regards,
James
