### ISSUE TITLE
node 6.9.x issue

### ISSUE THREAD

**Issue by tamasmahr** [dougmoscrop/serverless-http#21]
Hi,

Is this tested on node-6.9.1? I am trying this with a koa-1.4 app, with a simple code that throws a 401 error (``this.throw(`Unauthorized: ${this.request.method} ${this.request.url}`, 401);``), but this error never reaches the aws lambda service. I always get a timeout error from aws lamda.

Thank you for your help!

Tamas

**Comment by dougmoscrop** [comment]
It's unit tested with Node 6 in Travis:
https://github.com/dougmoscrop/serverless-http/blob/master/.travis.yml#L5

But I do not have any integration tests yet; I'll try to have a look soon

**Comment by tamasmahr** [comment]
I should add that the code gets as far as calling the handler. I see the console log output right before the throw. I suspect that the second `finish(response, event, context, options.response)` fails somehow.

Thanks for having a look at it!

Tamas

**Comment by tamasmahr** [comment]
I found the problem. My koajs app connects to a database, which prevents the lambda function to terminate. If I set `ctx.callbackWaitsForEmptyEventLoop = false;` in the lambda function, it works like a charm.

**Comment by dougmoscrop** [comment]
Sorry, finally pushed this in 1.4.3
