### ISSUE TITLE
[v3.0.0] [Typescript] Type definitions not part of the package

### ISSUE THREAD

**Issue by paulsouche** [dougmoscrop/serverless-http#230]
Hello !

`serverless-http.d.ts` is not part of the package anymore. This breaks the typings

![image](https://user-images.githubusercontent.com/5860504/161567403-829ea7b7-7259-492c-b2fa-7f16c5dbef7a.png)

I could help to fix the issue but I don't know how you publish this. I thought there was a `"files"` key in `package.json` that could explain the issue but no :cry: 

Thank you anyway for the great job !

**Comment by dougmoscrop** [comment]
ahh I accidentally left in in .npmignore after experimenting with bundling the definitions - can you try 3.0.1?
