### ISSUE TITLE
AWS custom authorizer support

### ISSUE THREAD

**Issue by jonni-larjomaa** [dougmoscrop/serverless-http#27]
Hi,

We are using APIG authorizers in our project and they were not working with serverless http, the problem is that parameters coming from APIG authorizers are coming in event.requestContext object, I can do the fixes to current Request object and send a PR.

Suggestion:

in request object the event.requestContext.auhtorizers is mapped to req.authorizers

EDIT: will close this, just figured out that I can use transformers doing this. maybe there could be a more accurate example made thou for using transformers, and that documentation should be put to the front page :)

**Comment by dougmoscrop** [comment]
For sure. Also feel free to re-open this and make it about the documentation instead.
