### ISSUE TITLE
TypeError: Cannot read property remoteAddress of undefined

### ISSUE THREAD

**Issue by nicka** [dougmoscrop/serverless-http#3]
This pops up when combined with [morgan](https://github.com/expressjs/morgan).

**Comment by dougmoscrop** [comment]
Thanks for the issue! The only reference to `remoteAddress` I can see in morgan is: https://github.com/expressjs/morgan/blob/1533cdcc512f4daf20a93cb0ab3b18d6563a897f/index.js#L468 which is guarded against connection being undefined. Do you have a stack trace or are you on a previous version of morgan?

I will look in to setting up `connection` with a remoteAddress based on the `context.identity`, not sure if that's reliable or not.

**Comment by nicka** [comment]
We're using:

```
morgan@^1.7.0:
  version "1.7.0"
```

Full stacktrace:

```
TypeError: Cannot read property 'remoteAddress' of undefined
at forwarded (/var/task/node_modules/forwarded/index.js:30:34)
at alladdrs (/var/task/node_modules/proxy-addr/index.js:53:15)
at proxyaddr (/var/task/node_modules/proxy-addr/index.js:225:15)
at IncomingMessage.ip (/var/task/node_modules/express/lib/request.js:341:10)
at getip (/var/task/node_modules/morgan/index.js:458:13)
at logger (/var/task/node_modules/morgan/index.js:107:26)
at Layer.handle [as handle_request] (/var/task/node_modules/express/lib/router/layer.js:95:5)
at trim_prefix (/var/task/node_modules/express/lib/router/index.js:312:13)
at /var/task/node_modules/express/lib/router/index.js:280:7
at Function.process_params (/var/task/node_modules/express/lib/router/index.js:330:12)
```

**Comment by dougmoscrop** [comment]
Can you try with 1.0.6?

**Comment by nicka** [comment]
@dougmoscrop sorry for the late response! 1.0.6 does not seem to be available. You need any help on this?

**Comment by nicka** [comment]
BTW this is not a huge issue for us! We considering other logging modules.

**Comment by dougmoscrop** [comment]
Is there any change you're hitting an npm cache or something?

https://www.npmjs.com/package/serverless-http says 1.0.6 is the latest, and I did a fresh `npm install serverless-http` and `cat node_modules/serverless-http/package.json` says 1.0.6!

**Comment by nicka** [comment]
I thought you meant `morgan` 🙈  Will check right away

**Comment by nicka** [comment]
Oke checked it's no longer throwing errors 👍 

But it's missing some log information within Lambda:

```
- - GET /api/v2.0/bands/4a6b562e-ab0e-43e5-93f8-d2f260cf2dc4/members HTTP/1.1 - - - - ms
```

Local:

```
::ffff:127.0.0.1 - GET /api/v2.0/bands/4a6b562e-ab0e-43e5-93f8-d2f260cf2dc4/members HTTP/1.1 200 318 - 2.022 ms
```

**Comment by dougmoscrop** [comment]
Ok, I will poke around!

**Comment by dougmoscrop** [comment]
The lack of response time is definitely because `on-headers` is never triggered; this is an excellent test case that I will add. i think the other missing data isn't as big a deal (I just have to set the right properties on the req/res objects).

**Comment by nicka** [comment]
@dougmoscrop Awesome 👍

**Comment by dougmoscrop** [comment]
`serverless-http@1.20` now uses the core http request/response objects and should behave 'normally' vs. the mocking library - this should be fixed! Feel free to reopen if not :D

**Comment by nicka** [comment]
@dougmoscrop Oeeeeh, will test right away 👍

**Comment by nicka** [comment]
This works great!

```
83.84.136.223 - GET /api/v2.0/bands/4a6b562e-ab0e-43e5-93f8-d2f260cf2dc4/members HTTP/1.1 200 402 - 141.634 ms
```
