### ISSUE TITLE
Include baseUrl in request object

### ISSUE THREAD

**Issue by XuluWarrior** [dougmoscrop/serverless-http#35]
The endpoint for lambdas will have the stage as their baseUrl.  However, currently, requests sent to the wrapped express app don't include this.  This means that redirects will not work as expected.

e.g. a request to an express.static directory path without the trailing "/" attempts to redirect to the same path appended with "/".  But when wrapped in serverless-http the redirect is wrong.

https://{host}/**{stage}**/staticdir => https://{host}/staticdir/

**Comment by XuluWarrior** [comment]
Similarly originalUrl should be set and equal to baseUrl + url

**Comment by dougmoscrop** [comment]
Hmm, I think I understand. I run all of my serverless-http lambdas behind a Custom Domain that is at root - e.g. myapi.foo.com -- stage is never part of it. (In other words, I use an empty base path mapping).

I will do some testing to see if the baseUrl is correct when using a Custom Domain in order to make sure this works for both cases (with or without base path mapping)

**Comment by XuluWarrior** [comment]
I've created a pull request with my suggested changes.  It includes both my original thought of just making the baseUrl = /{stage} (now commented out) as well a possibly more robust solution.

I thought I would try using serverless-offline for debugging and I noted that the offline server doesn't include stage in the path.  Nor does it provide a value for event.requestContext.path.

By comparing event.path with event.requestContext.path, I'm hoping that that will cover the cases of
- default deployment
- custom domains and 
- serverless-offline (which I guess is a special case of custom domains)

**Comment by XuluWarrior** [comment]
I set up a custom domain to test my changes and they work as expected.  (Or at least as I would expect.)

**Comment by lfreneda** [comment]
same issue, news?

**Comment by dougmoscrop** [comment]
Sorry, the other PR does not fix it and breaks things for offline mode and I don't think works the way one would expect.

**Comment by XuluWarrior** [comment]
@dougmoscrop Thanks for looking into this.

I wrote up my particular use case in https://github.com/dougmoscrop/serverless-http/pull/42#issuecomment-383576214

The key point is that express.static attempts to take into account mounting on relative URLs and uses baseURL or originalURL (I forget which now without looking at the code again) to do this.

**Comment by dougmoscrop** [comment]
OK, I will add these properties and hope that it doesn't interfere, but for an actual turnkey solution with the rest of the app routing infrastructure, especially cross-framework, I don't see how some userland configuration isn't necessary.

I was looking in to hacking on the router stuff in express to try to do something like this (it doesn't work of course)

```js
// in serverless-http
module.exports = (app, opts) => (event) => 
  const handler = getHandler(app);
  const request = new Request();
  app.mountpath = getEffectiveMountPath(event)
  handler(...)
  app.mountpath = '/' // put it back for subsequent requests
```

Basically, "dynamically mount" the apps per request.

**Comment by dougmoscrop** [comment]
We pass in a `http.IncomingRequest` to express/koa/etc. just like if there were a server, `baseUrl` and `originalUrl` are not part of this API/contract, so I don't think this is appropriate. These are concepts that you define in your application when you mount it, probably via some environment variable
