### ISSUE TITLE
req.connection.address is not a function

### ISSUE THREAD

**Issue by jguepin** [dougmoscrop/serverless-http#39]
I am using the [`bugsnag`](https://github.com/bugsnag/bugsnag-node) error middleware to report errors with Express.
The middleware makes `serverless-http` crash, as `req.connection.address()` is not defined.

Maybe `serverless-http` could implement this method, as other Express/Connect middlewares probably use it?

See https://github.com/bugsnag/bugsnag-node/issues/129 for details about the error.

**Comment by dougmoscrop** [comment]
Looks like you already added defensive code for this but I stubbed address() as of 1.5.4 -- not sure if it's properly stubbed, but the port is there (hardcoded to 443).
