### ISSUE TITLE
How to integrate if you connect to MongoDB (or whatever non-AWS database)

### ISSUE THREAD

**Issue by rclai** [dougmoscrop/serverless-http#41]
Typically on an HTTP Express setup you would connect to the database before you start listening on a port. But since each request requires a brand new Lambda request, integrating MongoDb requires a connection ([possibly cached](https://www.mongodb.com/blog/post/optimizing-aws-lambda-performance-with-mongodb-atlas-and-nodejs)) to MongoDB per Lambda request.

What is the recommended place in this library to initialize this MongoDB connection before the request is handled?

 I was thinking that the MongoDB connection could be injected into the request object via an Express middleware, but I'm not sure if it's a good idea.

**Comment by albertomr86** [comment]
Hi @rclai 

To do my my bit.
This is how I've been doing.

*main.js* (expressjs app)

```javascript
import express from 'express';
import connectDatabase, { register as registerModels } from './boot/mongodb';

// Register mongoose models.
registerModels();

// Configure the app.
const app = express();
app.use(connectDatabase);

// Routes
app.use('/', require('./routes').default);

// Expose.
export default app;
```
I use the middleware `connectDatabase` because I have to query on all my endpoints. But you could use the middleware at routing level.

**Middleware**
```javascript

import mongoose from 'mongoose';

mongoose.Promise = require('bluebird');

// Reuse the connection.
let isConnected;

/**
 * Register all models to use:
 * let model = mongoose.model(<Model registered>)
 */
export const register = () => {
  try {
    require('/path/to/models/<user>');
  }
  catch(er) {
    // Ignore any error registering the models.
    // This is more likely in Dev mode after a Hot-Reload.
  }
};

/**
 * Connect to Mongodb.
 * @param done Callback to notify the result.
 * @returns {*}
 */
export const connect = (done) => {
  if (isConnected) {
    return done();
  }

  mongoose.connect(process.env.DB_DSN, (err) => {
    if (err) {
      return done(err);
    }

    isConnected = true;
    done();
  });
};

/**
 * Middleware to connect to database before execute a controller.
 * @param req  ExpressJS Request.
 * @param res  ExpressJS Response.
 * @param next Callback to notify when its done.
 */
export default (req, res, next) => {
  connect(next);
};
```

**Comment by rclai** [comment]
Thanks for the feedback guys.

**Comment by dougmoscrop** [comment]
I am going to close this based on the discussion, please re-open if you need more help.

**Comment by gauravsavanur07** [comment]
{
  "errorMessage": "Cannot find module './api/models/Restaurant'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:474:25)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)",
    "Object.<anonymous> (/var/task/handler.js:15:20)",
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)",
    "Module.require (module.js:596:17)",
    "require (internal/module.js:11:18)"
  ]
}

**Comment by gauravsavanur07** [comment]
i am getting this error on aws lambda

**Comment by gauravsavanur07** [comment]
module.exports.hello = async (event) => {
  return {
    statusCode: 200,
    body: JSON.stringify({
      message: 'Go Serverless v1.0! Your function executed successfully!',
      input: event,
    }),
  };

  // Use this code if you don't use the http event with the LAMBDA-PROXY integration
  // return { message: 'Go Serverless v1.0! Your function executed successfully!', event };
};
const connectToDatabase = require('./db');

const Restaurant = require('./api/models/Restaurant');

module.exports.create =  (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  connectToDatabase()
    .then(() => {
      Restaurant.create(JSON.parse(event.body))
        .then(Restaurant => callback(null, {
          statusCode: 200,
          body: JSON.stringify(Restaurant)
        }))
        .catch(err => callback(null, {
          statusCode: err.statusCode || 500,
          headers: { 'Content-Type': 'text/plain' },
          body: 'Could not create the Restaurant.'
        }));
    }); 
};

module.exports.getOne = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  connectToDatabase()
    .then(() => {
      Restaurant.findById(event.pathParameters.id)
        .then(Restaurant => callback(null, {
          statusCode: 200,
          body: JSON.stringify(Restaurant)
        }))
        .catch(err => callback(null, {
          statusCode: err.statusCode || 500,
          headers: { 'Content-Type': 'text/plain' },
          body: 'Could not fetch the Restaurant.'
        }));
    });
};

module.exports.getAll = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  connectToDatabase()
    .then(() => {
      Restaurant.find()
        .then(Restaurants => callback(null, {
          statusCode: 200,
          body: JSON.stringify(Restaurants)
        }))
        .catch(err => callback(null, {
          statusCode: err.statusCode || 500,
          headers: { 'Content-Type': 'text/plain' },
          body: 'Could not fetch the Restaurants.'
        }))
    });
};

module.exports.update = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  connectToDatabase()
    .then(() => {
      Restaurant.findByIdAndUpdate(event.pathParameters.id, JSON.parse(event.body), { new: true })
        .then(Restaurant => callback(null, {
          statusCode: 200,
          body: JSON.stringify(Restaurant)
        }))
        .catch(err => callback(null, {
          statusCode: err.statusCode || 500,
          headers: { 'Content-Type': 'text/plain' },
          body: 'Could not fetch the Restaurants.'
        }));
    });
};

module.exports.delete = (event, context, callback) => {
  context.callbackWaitsForEmptyEventLoop = false;

  connectToDatabase()
    .then(() => {
      Restaurant.findByIdAndRemove(event.pathParameters.id)
        .then(Restaurant => callback(null, {
          statusCode: 200,
          body: JSON.stringify({ message: 'Removed Restaurant with id: ' + Restaurant._id, Restaurant: Restaurant })
        }))
        .catch(err => callback(null, {
          statusCode: err.statusCode || 500,
          headers: { 'Content-Type': 'text/plain' },
          body: 'Could not fetch the Restaurants.'
        }));
    });
};
