### ISSUE TITLE
Route not found

### ISSUE THREAD

**Issue by albertomr86** [dougmoscrop/serverless-http#43]
Hi.

I love this package. :1st_place_medal: 

I'm getting 404 for all endpoints after upgrade to 1.5.4.
The cause is the new way to find the path before pass it to the request (https://github.com/dougmoscrop/serverless-http/commit/5fc27b2c3db6f55096075b93ce8544fffe2af8c9#diff-4f98820926ab9e533c0e3ef619e49f66R10)

The follow line always return '/' because the route is in event.path.
```javascript
event.requestContext.path = event.requestContext.path || '/';
```

I moved on with this workaround:
```javascript
'use strict';

import serverless from 'serverless-http';
import app from './app/main';

export const handler = serverless(app, {
  request: function(request, event, context) {
    if (process.env.IS_OFFLINE) {
      event.requestContext.path = event.path || event.requestContext.path;
      request.url = event.requestContext.path;
    }
  }
});
```

Did I missed something?

**OS**: Ubuntu 16.04
**NodeJS**: v6.9.1
**serverless**: 1.26.1
**serverless-offline**: v3.18.0

**Comment by dougmoscrop** [comment]
Sorry about that. Are you saying this happens only with the offline plugin? Or it happens when deployed too?

**Comment by albertomr86** [comment]
I haven't tried it in production, right now I'm developing. I think I could try to deploy it and see what happens.

**Comment by dougmoscrop** [comment]
Should be fixed can you please let me know?

**Comment by albertomr86** [comment]
:+1: Thank you.
It's working again.
