### ISSUE TITLE
Always call default route

### ISSUE THREAD

**Issue by taufiqurrahman** [dougmoscrop/serverless-http#44]
why always call "/" route after upgrade to 1.5.4 ?
my code is : 

```javascript
const express = require('express');
const serverless = require('serverless-http');
const app = express()

//first route
//always call this
app.get('/', function (req, res) {
	res.send('Hello World!')
})

//the second route
//never call this
app.get('/test', function (req, res) {
	  res.send('Hello Test!')
})

module.exports.handler =  serverless(app);
```

**Comment by dougmoscrop** [comment]
Does this happen when deployed or when using some kind fo emulator/offline thing?

**Comment by taufiqurrahman** [comment]
offline

**Comment by dougmoscrop** [comment]
Ok, it sounds like the offline plugin doesn't correctly simulate Lambda but I can work around that. I'll release a fix in a couple hours.

**Comment by taufiqurrahman** [comment]
nice, thank you @dougmoscrop

**Comment by michaellashinsky** [comment]
I ran into this issue when using serverless-offline and serverless-dynamodb-local for local development

**Comment by dougmoscrop** [comment]
Should be fixed in latest

**Comment by michaellashinsky** [comment]
Tested in my environment and is working.  Thanks Doug!

**Comment by taufiqurrahman** [comment]
Its working now. Thanks @dougmoscrop
