### ISSUE TITLE
Expose the original event into the request for the app

### ISSUE THREAD

**Issue by ivanquirino** [dougmoscrop/serverless-http#47]
It would be nice if the original event from aws, the one that is given to the aws lambda handler, get exposed in the 'HttpRequest' object, so one could have access to it through `context.originalEvent`, in a koa example.

I had to write a wrapper like this to have access to the original event:

```javascript
function injectEvent(event, context, callback) {
  const app = new Koa();
  app.context.originalEvent = event;
  serverlessHttp(app)(event, context, callback)
}
```
I had expected that the framework somehow provided this but it is not the case. Every framework gives us the original http request so I think that's the right place. Well, if I'm wrong please tell me why.

**Comment by dougmoscrop** [comment]
You can use a request transformation as documented [here](https://github.com/dougmoscrop/serverless-http#requestresponse-transforms)

```js
module.exports.handler = serverless(app, {
  request: function(request, event, context) {
    request.lambdaEvent = event;
    request.lambdaContext = context
  }
}
```

It's basically a similar way of doing what you did, though it is a bit less intrusive in terms of the app construction.

I'm not strongly opposed to just doing this all the time, but I wasn't sure why people would need it, or if I had missed some way of improving how the library handles things.

**Comment by dougmoscrop** [comment]
But it can't go on the "koa context", since this library doesn't know about koa, it goes on the request, so you'd still have to write some kind of middleware, or understand that you have to access this.req.originalEvent (not this.context)

**Comment by ivanquirino** [comment]
Sorry, I didn't notice that. That's a good, clear way to do it. Thanks!
