### ISSUE TITLE
Response last-modified: Tue, 01 Jan 1980 00:00:00 GMT

### ISSUE THREAD

**Issue by boyuan459** [dougmoscrop/serverless-http#48]
The last modified date is always last-modified: Tue, 01 Jan 1980 00:00:00 GMT, so it use caches all the time, how to change the last-modified time to real file update time

**Comment by dougmoscrop** [comment]
This doesn't seem related to this library; there are dozens of tests that assert all kinds of things about the response and this header isn't added by any of my code; you should probably look in to the web framework you're using or middleware in it.

A good thing to do is just take the app, and .listen() and then interact with it via CURL - it should behave the same. If it's not, please re-open with some more details and I will try to look at it!
