### ISSUE TITLE
Support for generic request listeners

### ISSUE THREAD

**Issue by rochdev** [dougmoscrop/serverless-http#5]
Right now only express/connect/koa are supported for handling the request. However, I think any function that has a valid signature for `http.createServer()` should work as a handler.

From quickly looking at the code it could be a simple additional block in `getHandler()`

```js
if (typeof app === 'function') {
  return app;
}
```

What do you think?

**Comment by dougmoscrop** [comment]
Sure I definitely want to support as many frameworks as possible!
