### ISSUE TITLE
request.originalUrl does not include the first path segment

### ISSUE THREAD

**Issue by jamestharpe** [dougmoscrop/serverless-http#57]
request.originalUrl does not include the stage path segment from API Gateway. 

Example of expected value: `/api-gateway-stage/my/route`

Example of actual value: `/my/route`

The correct path value is indicated in `event.requestContext.path`

**Comment by dougmoscrop** [comment]
Yeah, I think this is related to https://github.com/dougmoscrop/serverless-http/pull/36/files

The requestContex.path -- I thought it was "wrong" when you used a custom domain?

I could be remembering wrong, or it got fixed/changed, either way, I will get some sites deployed and figure out what works best for everyone (with and without stage names, custom domains, etc)

**Comment by bsdkurt** [comment]
I still think my pull request https://github.com/dougmoscrop/serverless-http/pull/42 is the correct fix for this. However, since it would require changes for existing users who don't use custom domains, it would need to be a major bump of serverless-http with an explanation of how to upgrade.

**Comment by dougmoscrop** [comment]
I think it's possible to build on it and make it do some kind of detection

**Comment by bsdkurt** [comment]
> The requestContex.path -- I thought it was "wrong" when you used a custom domain?

The problem with #42 was that people not using custom domains (Amazon endpoints) were not expecting the change in the path and their current code required changes to deal with the corrected behavior. Also offline support broke for them, most likely for the same reason but needs further investigation. See https://github.com/dougmoscrop/serverless-http/pull/42#issuecomment-376943435 for more details.

This https://github.com/dougmoscrop/serverless-http/pull/42#issuecomment-376981255 outlines the three use cases for endpoints and how the `event.path` and `event.requestContext.path` values change for each of the cases. 

If you are interested in taking another look, I can update #42 for head.

**Comment by dougmoscrop** [comment]
I'm still trying to figure out if this is solvable in a way that makes everyone happy.

**Comment by dougmoscrop** [comment]
There's new `baseUrl` support coming in the next version, which will normalize the path being sent to your application.  I think the _only_ way this can work is if you configure your application and this library to understand their mount point -- it's no different than trying to run an application behind nginx mounted underneath some additional /prefix -- it can work, but all the URLs will be messed up, and rewriting message bodies on the fly is not the business I want to be in!

**Comment by dougmoscrop** [comment]
The correct way to solve this is to use the `basePath` option introduced in `2.1.0` and use some kind of environment variable to set it, and configure it in all your application logic that generates URLs.

I'm pretty sure it is impossible to have an application in API Gateway that seamlessly works for both custom domains and bare (execute-api) endpoints that have a _different_ base path, i.e.

✔️ 
- myapi.com/dev/foo
- execute-api.amazonaws.com/dev/foo

❌ 
- myapi.com/foo
- execute-api.amazonaws.com/dev/foo
