### ISSUE TITLE
error defining handler

### ISSUE THREAD

**Issue by lucastan** [dougmoscrop/serverless-http#59]
Your sample code should be as such

```
const wrapped = serverless(app);
module.exports.handler = async (evt, ctx) => {
    return wrapped(evt, ctx);
}

```

**Comment by dougmoscrop** [comment]
thanks fixed

**Comment by lucastan** [comment]
Do we need the “await”?
I tried without await and it still works

**Comment by dougmoscrop** [comment]
You don't, but the there's no point in the async either... The example is missing the reason you would use it this way, either by awaiting before returning,  or awaiting the result and doing something after it
