### ISSUE TITLE
Support for Google Cloud Functions / Azure Functions

### ISSUE THREAD

**Issue by rochdev** [dougmoscrop/serverless-http#6]
I think it would be great as by supporting all providers this project has the potential to become the one serverless framework to rule them all. I don't know if this would fit the current scope of the project though. 

Otherwise I am thinking maybe of making another project using this one as its "lambda" adapter.

**Comment by dougmoscrop** [comment]
Interesting - I am up for it! I also know that the Serverless people are looking at making a generic function handler type interface: (I think the discussion is here: https://github.com/serverless/stdlib-nodejs/issues/14)

So I was thinking I might eventually move to 'that' interface -- thoughts?

**Comment by cometta** [comment]
how soon will you add support for GCF?

**Comment by dougmoscrop** [comment]
Google Cloud functions look almost like they have their own version of this module anyway "internally" because they give you a req and res object in their handler.

Have you tried just

app = koa()
...
app.callback()(req, res)

Without any library help?

**Comment by cometta** [comment]
yup, it's working.

**Comment by dougmoscrop** [comment]
I'm always up for PRs that can help with any issues around GCF or Azure

**Comment by Schlesiger** [comment]
It would be nice if this library was seamless across AWS Lambda, Google Cloud Functions, and Azure Functions, to prevent any vendor lock-in. I am experimenting this along with [Spotinst](https://spotinst.com/) but now need a way to tell Spotinst to only deploy this function with AWS.

**Comment by unixfox** [comment]
Do you have an idea/quick fix to make my function working under Azure?
Here is my code:
```
const express = require('express')
const sls = require('serverless-http')
const app = express()
app.get('/', function (req, res) {
  res.send('Hello World!')
})
module.exports.server = sls(app)
```

**Comment by dougmoscrop** [comment]
I have never looked in to Azure. What does a basic "200 ok" look like in
pure azure?

**Comment by dougmoscrop** [comment]
I refactored this library to support multiple providers, however I don't have any plans to implement them. PRs are welcome.

**Comment by joshuaquek** [comment]
Where can we find this refactored version? Would there be a branch for this?
