### ISSUE TITLE
Support for LoopBack 4

### ISSUE THREAD

**Issue by olconstant** [dougmoscrop/serverless-http#62]
The wrapper is really nice! Will it support LoopBack 4 one day?

**Comment by dougmoscrop** [comment]
I'm open to support, do you want to PR?

**Comment by joe-niland** [comment]
@dougmoscrop I added PR #118 - please let me know what you think

**Comment by dougmoscrop** [comment]
Released in `2.3.0`

**Comment by PerfectedApp** [comment]
@joe-niland any example of how to use it?
