### ISSUE TITLE
TypeError: req.socket.destroy is not a function

### ISSUE THREAD

**Issue by aequasi** [dougmoscrop/serverless-http#63]
Getting spammed with this error, not really sure why. Seems to happen when there might be an error, and then it just loops repeatedly

**Comment by dougmoscrop** [comment]
Sorry, I somehow missed the notification on this issue; is it still happening with latest version? if so can you give more details (stack, what web framework and version you're using, etc)

**Comment by kyeung2** [comment]
I'm also getting this issue

**Comment by kyeung2** [comment]
I resolved my issue: it was my mistake

the express handler was doing the following:


`if(condition(x)){
   res.send(text)
}
res.json(other)
`

adding an else block resolves my issue. 

`if(condition(x)){
   res.send(text)
}else{
   res.json(other)
}
`

**Comment by dougmoscrop** [comment]
oh wow. okay, either way stubbing socket.destroy is fine. I can do that.

**Comment by dougmoscrop** [comment]
I stubbed and tested this in 1.10, but as you say this is a corner case of the internal logic of when your app technically does something wrong
