### ISSUE TITLE
Express: query double encoding

### ISSUE THREAD

**Issue by karlismelderis** [dougmoscrop/serverless-http#74]
my index.js
```
const serverless = require('serverless-http');

const app = require('./src/app');

exports.handler = serverless(app);
```

I put lambda behind ELB
Send query ?query=(countryCode%3DUS)

express is receiving double encoded url:
```
/?query=%2528countryCode%253DUS%2529
```

Lambda is receiving query already encoded:
    "queryStringParameters": {
        "query": "%28countryCode%3DUS%29"
    },

**Comment by karlismelderis** [comment]
feels like we need to run querystring.unescape(str) fo query parameters
https://nodejs.org/api/querystring.html#querystring_querystring_unescape_str

**Comment by dougmoscrop** [comment]
I have not tried Lambda behind an ELB, wow!  Are you sure this is an issue that's caused by my library? This feels like a Lambda/ELB configuration type thing ?

**Comment by dougmoscrop** [comment]
Sorry I am going to close this due to inactivity, if you still need help I suggest trying a standalone Lambda just to see what is coming across from the ELB to troubleshoot further. Of course re-open if the regular Lambda is normal but it gets all messed up when you use this lib.

**Comment by panva** [comment]
Yes this is caused by the ALB and AWS does not acknowledge to fix, apparently they don't mind that the event differs between API Gateway and an ALB integration.

For Koa I do the following to get around this.

```
const serverless = require('serverless-http')
const app = require('./app')

const handler = serverless(app)

module.exports.handler = (event, context) => {
  Object.entries(event.queryStringParameters).forEach(([key, value]) => {
    event.queryStringParameters[key] = decodeURIComponent(value)
  })

  return handler(event, context)
}
```

**Comment by panva** [comment]
Here's my original [report](https://forums.aws.amazon.com/thread.jspa?messageID=879725).

**Comment by jsvaughan** [comment]
I think I'm seeing the same issue.  I am switching from apigw to alb and I'm finding that my url parameters are double encoded.   Given that supposedly alb doesn't provide decoded params but apigw does, is something in serverless encoding them?

**Comment by dndrsn** [comment]
FWIW, a modified version of @panva's solution that works for API Gateway and ALB at the same time... 

```javascript
const serverless = require('serverless-http');
const { forEach, get } = require('lodash');
const app = require('./app');

const handler = serverless(app);

module.exports.handler = (event, context) => {
  if (get(event, 'requestContext.elb')) {
    forEach(event.queryStringParameters, (value, key) => {
      event.queryStringParameters[key] = decodeURIComponent(value);
    });
  }
  return handler(event, context);
};
```

**Comment by bmathews** [comment]
We ran into this issue as well with ALB in front of our Lambda. `event.queryStringParameters` are encoded, but this line of code assumes they're decoded: https://github.com/dougmoscrop/serverless-http/blob/b3bcb9fe73718f02d474371cbf30c8a915fd858a/lib/provider/aws/create-request.js#L53-L56

We are using the workaround @dndrsn provided.
