### ISSUE TITLE
Cannot find module 'aws-lambda'

### ISSUE THREAD

**Issue by pintux** [dougmoscrop/serverless-http#78]
Since version 1.9.1 I'm getting this error when trying to compile my TypeScript source code.

```
node_modules/serverless-http/serverless-http.d.ts:1:35 - error TS2307: Cannot find module 'aws-lambda'.

import { Context, Callback } from "aws-lambda";
```
Before updating, same code always compiled. For example code compiled using version 1.9.0.

**Comment by dougmoscrop** [comment]
Sorry, I don't use TypeScript and just merged in the pull request but I did it manually and I think I forgot `"@types/aws-lambda": "^8.10.15"`. I will fix this.

**Comment by dougmoscrop** [comment]
Oh, actually no, I did add it: https://github.com/dougmoscrop/serverless-http/blob/master/package.json#L50

But it's a devDependency. I don't use TypeScript, but I imagine that it doesn't work this way (as a devDep)?

**Comment by pintux** [comment]
Hi, 
in your case, I think you should resolve simply adding "@types/aws-lambda" as e dependency (and not as devDep).

**Comment by dougmoscrop** [comment]
I belie this is fixed with it being optional
