### ISSUE TITLE
Missing authorization context on request

### ISSUE THREAD

**Issue by GiviMAD** [dougmoscrop/serverless-http#96]
I'm using a custom authorizer and the returned context is not propagated to my Koa middleware.
The problem is in serverless-http/lib/provider/aws/create-request.js implementation:
```
(event, options) => {
  const method = event.httpMethod;
  const query = event.multiValueQueryStringParameters || event.queryStringParameters;
  const baseUrl = event.requestContext.path.slice(0, -event.path.length);
  ...

  return new Request({
  ...
```
The event passed to this function has an authorizer inside its requestContext. Can we expose it through the returned Request object, or even expose the complete input event?

**Comment by abdennour** [comment]
Not sure why it's closed
